name: Compile Protobuf and Commit

on:
  workflow_dispatch:
  push:
    paths:
      - 'putting_dune/*.proto'
      - '.github/workflows/protobuf_compile.yml'

permissions:
  contents: write

jobs:
  compile_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Python packages
        run: |
          pip install protobuf
          pip install -e .

      - name: Compile protobuf files
        # We'll first fetch the site-packages so we can include TensorFlow protos
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          for proto_file in putting_dune/*.proto; do
            echo "Compiling ${proto_file}"
            protoc -I=$SITE_PACKAGES/tensorflow/include -I=. --python_out=. "$proto_file"
            git add --intent-to-add $proto_file
          done

      - name: Commit changes
        run: |
          if git diff --quiet; then
            git config user.name "GitHub Actions Bot"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add putting_dune/*_pb2.py
            git commit -m "Automatically compiled protobuf files"
            git push
          else
            echo "No changes detected."
          fi